name: Periodic Healthcheck

on:
  schedule:
    - cron: '*/10 * * * *'
  push:
    branches:
      - main

jobs:
  healthcheck:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Check deployed service URL
        id: healthcheck
        uses: jtalk/url-health-check-action@v4
        with:
          url: ${{ secrets.HEALTHCHECK_URL }}
          max-attempts: 3
          retry-delay: 10s

      - name: Log success message
        run: echo '✅ Healthcheck succeeded for URL ${{ secrets.HEALTHCHECK_URL }}'
        if: ${{ steps.healthcheck.outcome == 'success' }}

      - name: Log failure message
        run: echo "❌ Healthcheck failed for URL ${{ secrets.HEALTHCHECK_URL }}"
        if: ${{ steps.healthcheck.outcome == 'failure' }}