name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: build
        run: npm run build
      - name: Test
        run: npm test
      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: Trigger deployment
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
      
      - name: Success
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: info
          details: The app has been deployed
          description: Build succeeded
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
        if: ${{ success() && github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
      - name: Failure
        uses: rjstone/discord-webhook-notify@v1
        with:
          severity: error
          description: Build failed
          details: commit ${{ github.event.head_commit.url }} broke the build
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
        if: ${{ failure() && github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}

  tag_release:
    needs: simple_deployment_pipeline
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Bump version and push tag
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
        uses: anothrNick/github-tag-action@1.71.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          DEFAULT_BUMP: 'patch'